namespace :db do
  description = "Populate the languages table with data"
  desc description
  task populate_languages: :environment do
    puts description
    languages = [
      {code: "ab", text: "Abkhazian"},
      {code: "aa", text: "Afar"},
      {code: "af", text: "Afrikaans"},
      {code: "ak", text: "Akan"},
      {code: "sq", text: "Albanian"},
      {code: "am", text: "Amharic"},
      {code: "ar", text: "Arabic"},
      {code: "an", text: "Aragonese"},
      {code: "hy", text: "Armenian"},
      {code: "as", text: "Assamese"},
      {code: "av", text: "Avaric"},
      {code: "ae", text: "Avestan"},
      {code: "ay", text: "Aymara"},
      {code: "az", text: "Azerbaijani"},
      {code: "bm", text: "Bambara"},
      {code: "ba", text: "Bashkir"},
      {code: "eu", text: "Basque"},
      {code: "be", text: "Belarusian"},
      {code: "bn", text: "Bengali"},
      {code: "bi", text: "Bislama"},
      {code: "bs", text: "Bosnian"},
      {code: "br", text: "Breton"},
      {code: "bg", text: "Bulgarian"},
      {code: "my", text: "Burmese"},
      {code: "ca", text: "Catalan, Valencian"},
      {code: "ch", text: "Chamorro"},
      {code: "ce", text: "Chechen"},
      {code: "ny", text: "Chichewa, Chewa, Nyanja"},
      {code: "zh", text: "Chinese"},
      {code: "cu", text: "Church Slavonic, Old Slavonic, Old Church Slavonic"},
      {code: "cv", text: "Chuvash"},
      {code: "kw", text: "Cornish"},
      {code: "co", text: "Corsican"},
      {code: "cr", text: "Cree"},
      {code: "hr", text: "Croatian"},
      {code: "cs", text: "Czech"},
      {code: "da", text: "Danish"},
      {code: "dv", text: "Divehi, Dhivehi, Maldivian"},
      {code: "nl", text: "Dutch, Flemish"},
      {code: "dz", text: "Dzongkha"},
      {code: "en", text: "English"},
      {code: "eo", text: "Esperanto"},
      {code: "et", text: "Estonian"},
      {code: "ee", text: "Ewe"},
      {code: "fo", text: "Faroese"},
      {code: "fj", text: "Fijian"},
      {code: "fi", text: "Finnish"},
      {code: "fr", text: "French"},
      {code: "fy", text: "Western Frisian"},
      {code: "ff", text: "Fulah"},
      {code: "gd", text: "Gaelic, Scottish Gaelic"},
      {code: "gl", text: "Galician"},
      {code: "lg", text: "Ganda"},
      {code: "ka", text: "Georgian"},
      {code: "de", text: "German"},
      {code: "el", text: "Greek, Modern (1453–)"},
      {code: "kl", text: "Kalaallisut, Greenlandic"},
      {code: "gn", text: "Guarani"},
      {code: "gu", text: "Gujarati"},
      {code: "ht", text: "Haitian, Haitian Creole"},
      {code: "ha", text: "Hausa"},
      {code: "he", text: "Hebrew"},
      {code: "hz", text: "Herero"},
      {code: "hi", text: "Hindi"},
      {code: "ho", text: "Hiri Motu"},
      {code: "hu", text: "Hungarian"},
      {code: "is", text: "Icelandic"},
      {code: "io", text: "Ido"},
      {code: "ig", text: "Igbo"},
      {code: "id", text: "Indonesian"},
      {code: "ia", text: "Interlingua (International Auxiliary Language Association)"},
      {code: "ie", text: "Interlingue, Occidental"},
      {code: "iu", text: "Inuktitut"},
      {code: "ik", text: "Inupiaq"},
      {code: "ga", text: "Irish"},
      {code: "it", text: "Italian"},
      {code: "ja", text: "Japanese"},
      {code: "jv", text: "Javanese"},
      {code: "kn", text: "Kannada"},
      {code: "kr", text: "Kanuri"},
      {code: "ks", text: "Kashmiri"},
      {code: "kk", text: "Kazakh"},
      {code: "km", text: "Central Khmer"},
      {code: "ki", text: "Kikuyu, Gikuyu"},
      {code: "rw", text: "Kinyarwanda"},
      {code: "ky", text: "Kirghiz, Kyrgyz"},
      {code: "kv", text: "Komi"},
      {code: "kg", text: "Kongo"},
      {code: "ko", text: "Korean"},
      {code: "kj", text: "Kuanyama, Kwanyama"},
      {code: "ku", text: "Kurdish"},
      {code: "lo", text: "Lao"},
      {code: "la", text: "Latin"},
      {code: "lv", text: "Latvian"},
      {code: "li", text: "Limburgan, Limburger, Limburgish"},
      {code: "ln", text: "Lingala"},
      {code: "lt", text: "Lithuanian"},
      {code: "lu", text: "Luba-Katanga"},
      {code: "lb", text: "Luxembourgish, Letzeburgesch"},
      {code: "mk", text: "Macedonian"},
      {code: "mg", text: "Malagasy"},
      {code: "ms", text: "Malay"},
      {code: "ml", text: "Malayalam"},
      {code: "mt", text: "Maltese"},
      {code: "gv", text: "Manx"},
      {code: "mi", text: "Maori"},
      {code: "mr", text: "Marathi"},
      {code: "mh", text: "Marshallese"},
      {code: "mn", text: "Mongolian"},
      {code: "na", text: "Nauru"},
      {code: "nv", text: "Navajo, Navaho"},
      {code: "nd", text: "North Ndebele"},
      {code: "nr", text: "South Ndebele"},
      {code: "ng", text: "Ndonga"},
      {code: "ne", text: "Nepali"},
      {code: "no", text: "Norwegian"},
      {code: "nb", text: "Norwegian Bokmål"},
      {code: "nn", text: "Norwegian Nynorsk"},
      {code: "ii", text: "Sichuan Yi, Nuosu"},
      {code: "oc", text: "Occitan"},
      {code: "oj", text: "Ojibwa"},
      {code: "or", text: "Oriya"},
      {code: "om", text: "Oromo"},
      {code: "os", text: "Ossetian, Ossetic"},
      {code: "pi", text: "Pali"},
      {code: "ps", text: "Pashto, Pushto"},
      {code: "fa", text: "Persian"},
      {code: "pl", text: "Polish"},
      {code: "pt", text: "Portuguese"},
      {code: "pa", text: "Punjabi, Panjabi"},
      {code: "qu", text: "Quechua"},
      {code: "ro", text: "Romanian, Moldavian, Moldovan"},
      {code: "rm", text: "Romansh"},
      {code: "rn", text: "Rundi"},
      {code: "ru", text: "Russian"},
      {code: "se", text: "Northern Sami"},
      {code: "sm", text: "Samoan"},
      {code: "sg", text: "Sango"},
      {code: "sa", text: "Sanskrit"},
      {code: "sc", text: "Sardinian"},
      {code: "sr", text: "Serbian"},
      {code: "sn", text: "Shona"},
      {code: "sd", text: "Sindhi"},
      {code: "si", text: "Sinhala, Sinhalese"},
      {code: "sk", text: "Slovak"},
      {code: "sl", text: "Slovenian"},
      {code: "so", text: "Somali"},
      {code: "st", text: "Southern Sotho"},
      {code: "es", text: "Spanish, Castilian"},
      {code: "su", text: "Sundanese"},
      {code: "sw", text: "Swahili"},
      {code: "ss", text: "Swati"},
      {code: "sv", text: "Swedish"},
      {code: "tl", text: "Tagalog"},
      {code: "ty", text: "Tahitian"},
      {code: "tg", text: "Tajik"},
      {code: "ta", text: "Tamil"},
      {code: "tt", text: "Tatar"},
      {code: "te", text: "Telugu"},
      {code: "th", text: "Thai"},
      {code: "bo", text: "Tibetan"},
      {code: "ti", text: "Tigrinya"},
      {code: "to", text: "Tonga (Tonga Islands)"},
      {code: "ts", text: "Tsonga"},
      {code: "tn", text: "Tswana"},
      {code: "tr", text: "Turkish"},
      {code: "tk", text: "Turkmen"},
      {code: "tw", text: "Twi"},
      {code: "ug", text: "Uighur, Uyghur"},
      {code: "uk", text: "Ukrainian"},
      {code: "ur", text: "Urdu"},
      {code: "uz", text: "Uzbek"},
      {code: "ve", text: "Venda"},
      {code: "vi", text: "Vietnamese"},
      {code: "vo", text: "Volapük"},
      {code: "wa", text: "Walloon"},
      {code: "cy", text: "Welsh"},
      {code: "wo", text: "Wolof"},
      {code: "xh", text: "Xhosa"},
      {code: "yi", text: "Yiddish"},
      {code: "yo", text: "Yoruba"},
      {code: "za", text: "Zhuang, Chuang"},
      {code: "zu", text: "Zulu"}
    ]

    languages.each do |language|
      Language.find_or_create_by(code: language[:code], text: language[:text])
    end
  end
end