namespace :db do
  description = "Populate the books table with data"
  desc description
  task populate_books: :environment do
    puts description
    books = [{id: 1, title: "A Call to Medical Evangelism and Health Education"},
    {id: 2, title: "A Call To Stand Apart"},
    {id: 3, title: "A Sketch of the Christian Experience and Views of Ellen G. White"},
    {id: 4, title: "A Solemn Appeal"},
    {id: 6, title: "An Appeal to Mothers"},
    {id: 7, title: "An Appeal to the Youth"},
    {id: 8, title: "Child Guidance"},
    {id: 9, title: "Christ Triumphant"},
    {id: 10, title: "Christian Education"},
    {id: 11, title: "Christian Experience and Teachings of Ellen G. White"},
    {id: 12, title: "Christian Leadership"},
    {id: 13, title: "Christian Service"},
    {id: 14, title: "Christian Temperance and Bible Hygiene"},
    {id: 15, title: "Christ’s Object Lessons"},
    {id: 16, title: "Colporteur Ministry"},
    {id: 17, title: "Conflict and Courage"},
    {id: 18, title: "Confrontation"},
    {id: 19, title: "Counsels for the Church"},
    {id: 20, title: "Counsels on Health"},
    {id: 21, title: "Counsels on Sabbath School Work"},
    {id: 22, title: "Counsels on Stewardship"},
    {id: 23, title: "Counsels to Parents, Teachers, and Students"},
    {id: 24, title: "Counsels to Writers and Editors"},
    {id: 25, title: "Country Living"},
    {id: 26, title: "Darkness Before Dawn"},
    {id: 27, title: "Daughters of God"},
    {id: 28, title: "Early Writings"},
    {id: 29, title: "Education"},
    {id: 30, title: "Evangelism"},
    {id: 31, title: "Faith and Works"},
    {id: 32, title: "Fundamentals of Christian Education"},
    {id: 33, title: "God's Amazing Grace"},
    {id: 34, title: "Gospel Workers (1892/1893 ed.)"},
    {id: 35, title: "Gospel Workers (1915 ed.)"},
    {id: 36, title: "Heaven"},
    {id: 37, title: "Help In Daily Living"},
    {id: 38, title: "In Heavenly Places"},
    {id: 39, title: "Last Day Events"},
    {id: 40, title: "Letters to Young Lovers"},
    {id: 41, title: "Life Sketches of Ellen G. White"},
    {id: 42, title: "Life Sketches of James White and Ellen G. White (1880 ed.)"},
    {id: 43, title: "Life Sketches of James White and Ellen G. White (1888 ed.)"},
    {id: 44, title: "Lift Him Up"},
    {id: 45, title: "Manual for Canvassers"},
    {id: 74, title: "Maranatha"},
    {id: 75, title: "Medical Ministry"},
    {id: 76, title: "Messages to Young People"},
    {id: 77, title: "Mind, Character, and Personality, vol. 1"},
    {id: 78, title: "Mind, Character, and Personality, vol. 2"},
    {id: 79, title: "My Life Today"},
    {id: 80, title: "Our Father Cares"},
    {id: 81, title: "Our High Calling"},
    {id: 83, title: "Pastoral Ministry"},
    {id: 84, title: "Patriarchs and Prophets"},
    {id: 86, title: "Peter’s Counsel to Parents"},
    {id: 87, title: "Prayer"},
    {id: 88, title: "Prophets and Kings"},
    {id: 89, title: "Reflecting Christ"},
    {id: 98, title: "Selected Messages Book 1"},
    {id: 99, title: "Selected Messages Book 2"},
    {id: 100, title: "Selected Messages Book 3"},
    {id: 101, title: "Sketches from the Life of Paul"},
    {id: 102, title: "Sons and Daughters of God"},
    {id: 103, title: "Special Testimonies On Education"},
    {id: 104, title: "Spiritual Gifts, vol. 1"},
    {id: 105, title: "Spiritual Gifts, vol. 2"},
    {id: 106, title: "Spiritual Gifts, vol. 3"},
    {id: 107, title: "Spiritual Gifts, vol. 4a"},
    {id: 108, title: "Steps to Christ"},
    {id: 109, title: "Supplement to the Christian Experience and Views of Ellen G. White"},
    {id: 110, title: "Temperance"},
    {id: 112, title: "Testimonies for the Church, vol. 8"},
    {id: 113, title: "Testimonies for the Church, vol. 5"},
    {id: 114, title: "Testimonies for the Church, vol. 4"},
    {id: 115, title: "Testimonies for the Church, vol. 9"},
    {id: 116, title: "Testimonies for the Church, vol. 1"},
    {id: 117, title: "Testimonies for the Church, vol. 7"},
    {id: 118, title: "Testimonies for the Church, vol. 6"},
    {id: 119, title: "Testimonies for the Church, vol. 3"},
    {id: 120, title: "Testimonies for the Church, vol. 2"},
    {id: 121, title: "Testimonies on Sabbath-School Work"},
    {id: 122, title: "Testimonies on Sexual Behavior, Adultery, and Divorce"},
    {id: 123, title: "Testimonies to Ministers and Gospel Workers"},
    {id: 124, title: "Testimonies to Southern Africa"},
    {id: 125, title: "Testimony Studies on Diet and Foods"},
    {id: 126, title: "That I May Know Him"},
    {id: 127, title: "The Acts of the Apostles"},
    {id: 128, title: "The Adventist Home"},
    {id: 130, title: "The Desire of Ages"},
    {id: 131, title: "The Faith I Live By"},
    {id: 132, title: "The Great Controversy"},
    {id: 133, title: "The Great Controversy (1888 ed.)"},
    {id: 135, title: "The Ministry of Healing"},
    {id: 137, title: "The Retirement Years"},
    {id: 138, title: "The Sanctified Life"},
    {id: 139, title: "The Southern Work"},
    {id: 140, title: "The Spirit of Prophecy, vol. 4"},
    {id: 141, title: "The Spirit of Prophecy, vol. 1"},
    {id: 142, title: "The Spirit of Prophecy, vol. 3"},
    {id: 143, title: "The Spirit of Prophecy, vol. 2"},
    {id: 144, title: "The Story of Jesus"},
    {id: 145, title: "The Story of Redemption"},
    {id: 146, title: "The Truth About Angels"},
    {id: 147, title: "The Upward Look"},
    {id: 148, title: "The Voice in Speech and Song"},
    {id: 149, title: "This Day With God"},
    {id: 150, title: "Thoughts From the Mount of Blessing"},
    {id: 151, title: "To Be Like Jesus"},
    {id: 152, title: "Welfare Ministry"},
    {id: 153, title: "Ye Shall Receive Power"},
    {id: 384, title: "Counsels on Diet and Foods"},
    {id: 385, title: "Spiritual Gifts, vol. 4b"},
    {id: 386, title: "A New Life (Revival and Beyond)"},
    {id: 387, title: "The Health Food Ministry"},
    {id: 388, title: "Healthful Living"},
    {id: 389, title: "Historical Sketches of the Foreign Missions of the Seventh-day Adventists"},
    {id: 390, title: "The Publishing Ministry"},
    {id: 806, title: "The Colporteur Evangelist"},
    {id: 1445, title: "A Word to the Little Flock"},
    {id: 2003, title: "Testimony Treasures, vol. 2"},
    {id: 2004, title: "Testimony Treasures, vol. 3"},
    {id: 2005, title: "Testimony Treasures, vol. 1"},
    {id: 2769, title: "From Trials to Triumph"},
    {id: 2771, title: "From Heaven With Love"},
    {id: 2772, title: "From Eternity Past"},
    {id: 2774, title: "From Here to Forever"},
    {id: 2775, title: "From Splendor to Shadow"},
    {id: 11267, title: "Christ Our Saviour"},
    {id: 11974, title: "True Revival"},
    {id: 12119, title: "Christ in His Sanctuary"},
    {id: 12210, title: "From the Heart"},
    {id: 12320, title: "The Great Hope (Condensed)"},
    {id: 12399, title: "Ministry to the Cities"},
    {id: 12557, title: "Notes of Explanation"},
    {id: 12862, title: "Homeward Bound"},
    {id: 13940, title: "With God at Dawn"},
    {id: 14039, title: "Radiant Religion"},
    {id: 14042, title: "God’s Remnant Church (The Remnant Church)"},
    {id: 14086, title: "The Impending Conflict"},
    {id: 14150, title: "Jesus, Name Above All Names"},
    {id: 14211, title: "Story of Hope"},
    {id: 14222, title: "Principles for Christian Leaders"}]

    books.each do |book_details|
      Book.find_or_create_by(id: book_details[:id], title: book_details[:title])
    end
  end
end